let
    DataMin = List.Min(fRespostasNPS[DATA_RESPOSTA]),
    DataMax = List.Max(fRespostasNPS[DATA_RESPOSTA]),
    QtdDias = Duration.Days (DataMax - DataMin) + 1,
    ListarDatas = List.Dates(DataMin, QtdDias, #duration(1,0,0,0)),
    #"Convertido para Tabela" = Table.FromList(ListarDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
    #"Trimestre Inserido" = Table.AddColumn(#"Tipo Alterado", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
    #"Prefixo Adicionado" = Table.TransformColumns(#"Trimestre Inserido", {{"Trimestre", each "TRI 0" & Text.From(_, "pt-BR"), type text}}),
    #"Mês Inserido" = Table.AddColumn(#"Prefixo Adicionado", "Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Nome do Mês Inserido", "Primeiros caracteres", each Text.Start(Text.Upper([Nome do Mês]), 3), type text),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Primeiros Caracteres Inseridos",{{"Primeiros caracteres", "Mês Abreviado"}}),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Colunas Renomeadas1", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Semana do Ano Inserida1" = Table.AddColumn(#"Semana do Ano Inserida", "Semana do Ano.1", each Date.WeekOfYear([Data]), Int64.Type),
    #"Colunas Removidas" = Table.RemoveColumns(#"Semana do Ano Inserida1",{"Semana do Ano.1"}),
    #"Semana do Mês Inserida" = Table.AddColumn(#"Colunas Removidas", "Semana do Mês", each Date.WeekOfMonth([Data]), Int64.Type),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Semana do Mês Inserida",{"Data", "Trimestre", "Mês", "Nome do Mês", "Mês Abreviado", "Semana do Mês", "Semana do Ano"}),
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Reordenadas", "Semestre", each if [Mês] >= 6 then "SEM 01" else "SEM 02"),
    #"Dia do Ano Inserido" = Table.AddColumn(#"Coluna Condicional Adicionada", "Dia do Ano", each Date.DayOfYear([Data]), Int64.Type)
in
    #"Dia do Ano Inserido"